# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from functools import partial

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469, 402)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(11, 310, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 46, 60, 16))
        self.label.setLineWidth(11)
        self.label.setMidLineWidth(3)
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 189, 24, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(11, 68, 24, 16))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(11, 211, 441, 92))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(11, 90, 441, 92))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 10, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        # MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 26))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(self.First_click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Dialog", "汇率转换器"))
        self.pushButton.setText(_translate("Dialog", "转换"))
        self.label.setText(_translate("Dialog", "汇率转换"))
        self.label_2.setText(_translate("Dialog", "USD"))
        self.label_3.setText(_translate("Dialog", "CNY"))
        self.pushButton_2.setText(_translate("Dialog", "Exit"))

    def First_click(self):
        QtWidgets.QMessageBox.information(self.pushButton_2, '错误', '请重试')



class Dialog(QtWidgets.QDialog):
    def closeEvent(self,event):
        print('1')
        reply = QtWidgets.QMessageBox.question(self,
                                               '提示',"你确定要退出吗？",
                                               QtWidgets.QMessageBox.Yes|QtWidgets.QMessageBox.No,
                                               QtWidgets.QMessageBox.No)
        if reply == QtWidgets.QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()



if __name__ =='__main__':
    app = QtWidgets.QApplication(sys.argv)
    parent = Dialog()
    sub = Ui_Dialog()
    sub.setupUi(parent)
    parent.show()
    sys.exit(app.exec_())